version: '3.1'
services:
  datastream:
    build:
      context: ../..
      dockerfile: ./toys/code_api_DC/Dockerfile
    restart: always
    ports:
      - 4041:4041
    entrypoint:
      [
        "/app/.venv/bin/python",
        "-m",
        "uvicorn",
        "--host",
        "0.0.0.0",
        "--port",
        "4041",
        "toys.code_api_DC.api:api",
        "--reload"
      ]
