version: '3.1'
services:
  datastream:
    build:
      context: ../..
      dockerfile: ./toys/code_api_DC/Dockerfile
    restart: always
    command:
      [
        "/app/.venv/bin/python",
        "uvicorn --host '0.0.0.0' --port 4041 api:api --reload"
      ]
