version: '3.1'
services:
  datastream:
    build:
      context: ../..
      dockerfile: ./toys/code_data_stream/Dockerfile
    restart: always
    command: ["/app/.venv/bin/python", "/app/toys/code_data_stream/generate.py"]